

<h1 style="box-sizing: border-box; margin: 48px 0px 25px -1.2em; font-size: 45px; font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-weight: 500; line-height: 1.1; color: rgb(255, 144, 0); padding-left: 1.2em; position: relative; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
Three-Level distribution</span></h1>
<hr style="box-sizing: content-box; height: 0px; margin-top: 20px; margin-bottom: 20px; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" /><o:p style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"></o:p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Three-Level distribution model Description:</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
1. As long as you apply directly to become a】 【Feng goods distributors, gently
point can be generated exclusively in the "own mall", and then you】 【Commodities
in the exchange of goods can get commissions commission.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
2. If you buy goods in the】 【Maple goods feel good, you can】 【Maple Commodities
Department of the WeChat to promote the public [] or two-dimensional
distribution code】 【Maple Commodity Link to recommend your friends Or friends
circle, as long as they are concerned about the [WeChat] [micro-credit public
goods into the maple goods exchange】 【apply to become a distributor, the system
will automatically lock her for your subordinates.</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">If
your buddy is buying a product in [Maple], you and her have a commission.</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">She
can also link her to a friend or a friend's circle, and her friends in the mall
to buy goods, her friends, you and your friends have commission commission.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
3. Click the lower distributor chain development</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">at
all levels [distributors] Any number of</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">national
laws multilevel distribution of profits can only have three.</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">【Maple】
Department of the system will automatically lock the background distribution
chain three, so [maple goods exchange] is completely safe and legal multi-level
distribution platform, we only use innovative business model interpretation 【】.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
With the quality and service to establish trust, with a new interpretation of
the model Bao Cheng Mall!</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Three-Level distribution model example:</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(0, 128, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
<span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(0, 128, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
Distributor:</span><span class="Apple-converted-space">&nbsp;</span>ABCD ......</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
1. If you are</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">A,</span><span class="Apple-converted-space">&nbsp;</span>you
buy</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: sans-serif; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">goods</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">from<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">1,000</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">[maple]
Collection mall<span class="Apple-converted-space">&nbsp;</span>where</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">you
can get a commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">130</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(13%).</span></span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
2. If you are</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">A,</span><span class="Apple-converted-space">&nbsp;</span>you
develop a</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B,</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">buy
commodities from 1,000 yuan [Mall] Collection Maple Lane, then</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">can
get commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">130</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(13%),</span><span class="Apple-converted-space">&nbsp;</span>as
a</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">parent</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">you</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">can
get a commission of</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">100</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(10%).</span></span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
3. If</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">the
development of</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">C</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B,</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">C</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: sans-serif; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">1,000</span><span class="Apple-converted-space">&nbsp;</span>yuan
of goods</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">purchased
from the Collection Mall] [Maple<span class="Apple-converted-space">&nbsp;</span>Lane,</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">then</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">C</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">can
get commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">130</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(13%),</span><span class="Apple-converted-space">&nbsp;</span>B</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">as</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">C</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">superiors
can get commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">100</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(10%)</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">,</span><span class="Apple-converted-space">&nbsp;</span>a</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">as
the</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">parent
can get the commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">70</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(7%).</span></span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
4. If</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">the
development of the</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">D</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">C,</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">D</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">purchased
from the Collection Mall] [Maple Lane</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: sans-serif; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">$<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">1000,</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">then</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">D</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">can
get commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">130</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(13%),</span><span class="Apple-converted-space">&nbsp;</span>C</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">D</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">as
a</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">parent
can get the commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">100</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(10%),</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">B</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">as</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">C</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">superiors
can get commission</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">70</span></span><span class="Apple-converted-space">&nbsp;</span>(7%),
a</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">is
no commission.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: sans-serif; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Note: Some products are in accordance with the profit PV share commission.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(0, 100, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
Three distribution mode protection:</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
1. Your friends as long as your WeChat through the public [] to promote the
distribution of two-dimensional code】 【Note】 【Maple Commodity Exchange mall or
through the link】 【mall application to become a distributor, the system will
permanently lock you into your subordinate distribution Quot;</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
2. We take three rebate policy, precision lock every potential customer, each of
our goods have come up with</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30%</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">of</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">the</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">profits,
so that distributors are layers of benefit.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
3. You only need to open your own [my commission], you will be able to clearly
know the number of individual sub-distributors and trading order details.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
4. We customize the commission settlement system for you, each order through the
system to confirm, the commission automatically assigned to your binding payment
account, you need to issue 【apply for cash】, your commission on the order
proceeds, the system will automatically transfer To your personal account.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
How to make money fast?</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
In this universal micro-mobile Internet era, whether you have annoyed friends
circle full screen ads, but also envy them to have their own money to
micro-shop!</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">Have
you ever had a dream and suffer no derivative time and money to achieve, with
the "micro-distribution" pace,</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">three</span><span class="Apple-converted-space">&nbsp;</span>minutes</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">to
teach you Fun micro-marketing, a "maple products Huida man" easily make
millions!Please read the following text carefully, learning</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">new<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">2015</span><span class="Apple-converted-space">&nbsp;</span>derivative
mode: "fission chain" marketing model</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
1, simple and fast to become a dealer</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
The first "chain fission" marketing features, to achieve sharing, purchase,
payment, distribution, statistics and other powerful integrated distribution
system, do not shop, as long as concerned about the purchase of any product, you
can become Maple Suppliers) ",</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">get
your exclusive promotion of two-dimensional code</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">(after
the purchase, in a custom menu: service → I get promotional link or image), your
friends through your exclusive two-dimensional code to make a purchase, you can<span class="Apple-converted-space">&nbsp;</span>get</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">10%</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">Direct
dividends! Sitting so money is so simple, from making money continuously.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
2, fission-type development of goods dealers, would like to block stopped</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Chain fission patterns, detonated social networking, rapid fission development
"dealers."</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">"Dealer"
In addition to their own two-dimensional code points infrared, friends once your
attention through the two-dimensional code, "Feng Commodities Meeting", life
tied into your next home, other people through his two-dimensional code to buy
you You can get</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">7%</span><span class="Apple-converted-space">&nbsp;</span>indirect
benefit-!</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
3, make good use of a circle of friends, the money earned together</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Let employees, customers, friends are recommended and sell your products, a huge
circle of friends, trusted word of mouth recommendation, brand exposure and
sales transactions to promote each other, the transaction will be able to
commission.</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">No
matter who you are under the home, it does not matter, you make money and your
next home only has a relationship, that is your next home you earn more.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 12pt;">
4, more ways to open up your customer channels</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
In addition to the use of micro-channel circle of friends, you can put your
unique two-dimensional code image through</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">QQ,</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">QQ</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">group,
community forums, paste it,</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">in
any way</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">QQ</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">space,
watercress, websites and other published to anything you can imagine a place,
and as long as the call Users sweep your two-dimensional code sweep, to
purchase, you can easily make money!</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">Now
I come to calculate for you:</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Suppose you have only</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30</span><span class="Apple-converted-space">&nbsp;</span>promotion
customers!</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Each person has hundreds of contacts in the micro-channel micro-channel friend,
also sell goods, to see how we are marketing, we just assume that you're
promoting</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">a</span><span class="Apple-converted-space">&nbsp;</span>customers</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">every<span class="Apple-converted-space">&nbsp;</span>day,and
a month is down</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30</span><span class="Apple-converted-space">&nbsp;</span>clients:</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
A<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">Member:</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30,000</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">*
1000</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">*
13%</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">3900</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">rebate</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Two</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">members:</span><span class="Apple-converted-space">&nbsp;</span>your</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30</span><span class="Apple-converted-space">&nbsp;</span>customers
per</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">person
is equivalent to</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">to
promote</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">900</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">900,000</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">*
1000</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">*
10%</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">90,000</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">rebate</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Three<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">members:</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">the
promotion of</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">30</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">900</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">customers
per</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">person
is equivalent to</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">27,000</span></span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">27</span><span class="Apple-converted-space">&nbsp;</span>million
yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">*
1000</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">*
7%</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">1.89</span><span class="Apple-converted-space">&nbsp;</span>million
yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">rebate</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
+90000</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">Yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">3900
yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">=</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(255, 0, 0); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">1,983,900</span><span class="Apple-converted-space">&nbsp;</span>yuan</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">+1890000</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
So now doing, from start to finish you did not spend a penny, you only
recommendation products to close friends, you will get a monthly</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">income
of</span><span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: sans-serif; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">more</span><span class="Apple-converted-space">&nbsp;</span>than
1.98 million<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">yuan!</span></span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">Of
course, this is a particularly ideal state, but you do not have to spend a penny
is possible to use their spare time to earn their own travel costs Why not!</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 16pt;">
<span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;">
<span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">
Our platform is fully in line with Tencent official requirements, that is,
product quality, low prices, commission rebates, good service, timely delivery,
commission clearing quickly and accurately, welcome to join the maple goods
exchange, experience new micro-business, and seek common development!</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">If
you advertise more friends, the monthly income of tens of thousands will no
longer be a dream, if you see here agree with us, you can immediately buy to
become a dealer, can also open the sleep mode to make money!</span></span><span class="Apple-converted-space">&nbsp;</span><span class="notranslate" onmouseout="_tipoff()" onmouseover="_tipon(this)" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: 宋体; color: rgb(51, 51, 51); letter-spacing: 0pt; font-weight: normal; text-transform: none; font-style: normal; font-size: 9pt;">.</span></span><o:p style="box-sizing: border-box;"></o:p></p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 15.75pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<p class="p" style="box-sizing: border-box; margin: 3.75pt 0pt; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;, NSimSun, serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0pt; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); line-height: 15.75pt;"><o:p style="box-sizing: border-box;"></o:p>
</p>
<br class="Apple-interchange-newline" />
