<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>特大喜报</title>
<style type="text/css">

p.p{
margin: 5.0000pt 0.0000pt;
	text-align:left;
	font-family:Calibri;
	font-size:12.0000pt;
}

span.15{
font-family:'Times New Roman';
font-weight:bold;
}

</style>
</head>

<body>

<h4 style="box-sizing: border-box; font-family: inherit; line-height: 1.1; color: grey; margin-top: 1em; margin-bottom: 0.1em; font-size: 18px; margin-left: -1.2em; padding-left: 1.2em; position: relative;">
<img class="img-responsive" alt=""  src="includes/sub_content/img/6358712196688449356484926.jpg" /><strong><br />
留学生安省提名计划（PNP）</strong></h4>


<p class="p">&nbsp;</p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 11.0000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">项目简介</font></span></b><b><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
&nbsp;获批的被提名申请人获颁省提名证书（Provincial Nomination Certificate）。「安省省提名」每年可以接受2500个申请。 
其中雇主担保移民是雇主向导的，这意味著作为个人，您只有在您僱主的申请被审核及批准之后，才能申请。一旦获批，「安省提名办公室」將向您的僱主提供一套候选人申请资料，转交给您。 
所有申请將按先来先办的原则办理，並根据该计划的標准进行审核评估。由於名额有限，我们鼓励僱主及早申请，以获得他们所需的名额</span><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p>
</span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 11.0000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">雇主担保移民项目优势</font></span></b><b><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">该申请分为两步：</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">1.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">雇主方面：雇主须向安省</font>PNP申请核准该职位。如获批准，将收到全套申请资料。</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">2.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人方面：雇主将全套申请资料转给申请人，后者按要求填写完毕，连同辅助材料（及认证翻译）和申请费提交安省</font>PNP。申请人无需提供语言成绩</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">3.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">如果申请人获得安省提名，即可申请配偶及子女全家移民。在等待移民签证期间，安省政府还可协助您取得临时工作许可，以合法留在安省。</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p>
</span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 11.0000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">申请条件</font></span></b><b><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">1.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人毕业后或即将毕业期间已获得工作职位（</font>job 
offer），即可申请安省省提名移民。申请人需满足以下条件：</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人至少有一半的高等教育是在加拿大公立院校完成的，并且已经顺利毕业或即将毕业于认可的加拿大公立学院或者大学；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人若无海外学位，在加拿大需完成至少两年的全日制专科或本科教育；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人若有海外学位，在加拿大需完成至少一年的全日制硕士学位或研究生文凭课程；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">已获得的工作职位必须满足</font>NOC 
O, A和B的职业要求，但不是必须与所学专业相关的职业；</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">工作职位必须是全职的，永久的，并且满足这个职业的薪资要求；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">有在加拿大的合法身份；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人必须在毕业两年内申请，也可在完成学业前的最后一个学期申请，后者需提供成绩单证明可以如期毕业。</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">2.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">安省在</font>2010年6月推出了International 
Masters Graduate Stream省提名项目，申请人需满足以下条件，即可申请:</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">有在安省工作定居的意向；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">在安省取得符合条件的公立大学的研究生学位；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">至少完成一年全日制硕士学位教育；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人必须在毕业两年内申请，也可在完成学业前的最后一个学期申请，后者需提供成绩单证明可以如期毕业；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人现在居住在安省境内；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人在申请期间的身份合法，可以持工签，学签或临时居留证；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">满足语言要求，英语满足雅思</font>G类考试达到听，说，读，写每项不少于6分，或法语满足TEF考试至少5分；</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">提供最低要求的资金证明（一般来说需要提供证明一年生活的资金证明，一个人满足</font>$11931加币以上）；</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">证明在提交申请前的两年内，至少有一年居住在安省；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">没有再深造的打算（比如获得其他学位或者进修博士，但若是为满足职业注册的需求也可选择深造）。</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">3.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">安省的</font>International 
PhD Graduate博士类别项目要求申请人满足以下条件:</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人在安省取得符合条件的公立大学的博士学位；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人成功完成博士学位所要求的全部项目；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">取得博士学位的学习时间不得少于</font>2年；</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人必须在取得学位的</font>2年内提出移民申请；</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人必须在申请期间保持合法身份；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; mso-ascii-font-family: Symbol; mso-hansi-font-family: Symbol; mso-bidi-font-family: Symbol; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">·<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">无需语言成绩。</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p>
</span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 11.0000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">可迁随的家属</font></span></b><b><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">以下家庭成员可随申请人同时获发居留证：</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">1.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">申请人配偶；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">2.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">未成年子女；</font></span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="p"><b>
<span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p>
</span></b></p>
<p class="p"><b>
<span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 11.0000pt; mso-font-kerning: 0.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<font face="微软雅黑">政府收取费用</font></span></b><b><span style="mso-spacerun:'yes';font-family:微软雅黑;color:rgb(68,68,68);letter-spacing:0.0000pt;font-weight:bold;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:0.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">1.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">安省</font>PNP申请费 
– 国际学生：$1,500；</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal"><![if !supportLists]>
<span style="font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 12.0000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);">
<span style="mso-list:Ignore;">2.<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; color: rgb(68,68,68); letter-spacing: 0.0000pt; font-weight: bold; text-transform: none; font-style: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt; background: rgb(255,255,255); mso-shading: rgb(255,255,255);"><font face="微软雅黑">联邦申请费：主申请</font>$550；配偶$550，及19岁以下子女$150。 
联邦审核通过（获体检表）获得签证前缴纳新移民登陆费，主申请人及配偶各$490。</span><span style="mso-spacerun:'yes';font-family:微软雅黑;font-weight:bold;font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></b></p>
<p class="MsoNormal">
<span style="mso-spacerun:'yes';font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>
&nbsp;</o:p></span></p>

</body>

</html>
